name: InstallKarpenter
description: 'Installs Go Downloads and installs Karpenter Dependencies'
inputs:
  account_id:
    description: "Account ID to access AWS"
    required: true
  role:
    description: "Role to access AWS"
    required: true
  region:
    description: "Region to access AWS"
    required: true
  ecr_account_id:
    description: "Account ID for the ECR repo"
    required: true
  ecr_region:
    description: "Region for the ECR repo"
    required: true
  cluster_name:
    description: 'Name of the cluster to be launched by eksctl'
    required: true
  k8s_version:
    description: 'Version of Kubernetes to use for the launched cluster'
    default: "1.28"
  webhooks_enabled:
    description: "Whether webhooks are enabled or not. Valid values are 'true' or 'false'"
    default: 'true'
  git_ref:
    description: "The git commit, tag, or branch to check out. Requires a corresponding Karpenter snapshot release"
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
    with:
      ref: ${{ inputs.git_ref }}
  - uses: ./.github/actions/e2e/install-helm
    with:
      version: v3.12.3 # Pinned to this version since v3.13.0 has issues with anonymous pulls: https://github.com/helm/helm/issues/12423
  - name: create karpenter namespace
    shell: bash
    run: |
      kubectl create ns karpenter || true
      kubectl label ns karpenter scrape=enabled --overwrite=true
      kubectl label ns karpenter pod-security.kubernetes.io/enforce=restricted --overwrite=true
  - name: login to ecr via docker
    uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
    with:
      registry: ${{ inputs.ecr_account_id }}.dkr.ecr.${{ inputs.ecr_region }}.amazonaws.com
      logout: true
  - name: install-karpenter
    shell: bash
    run: |
      ./test/hack/e2e_scripts/install_karpenter.sh
  - name: diff-karpenter
    shell: bash
    run: |
      helm diff upgrade --namespace kube-system \
        karpenter oci://${{ inputs.ecr_account_id }}.dkr.ecr.${{ inputs.ecr_region }}.amazonaws.com/karpenter/snapshot/karpenter \
        --version v0-$(git rev-parse HEAD) \
        --reuse-values --three-way-merge --detailed-exitcode --no-hooks
